GET http://localhost:3001/ 
###
GET http://localhost:3001/question?theme=Science%20sociale&niveau=facile
###

POST http://localhost:3001/users
Content-Type: "application/json"
Accept: "application/json"

{
    "nom":"halleg",
    "email":"halleg@gmail",
    "password":"1234"
}
###
GET http://localhost:3001/wikipedia/Java%20programming%20language 
###
GET  http://localhost:3001/allQuestions
